language: php
php:
- 7.1

sudo: false

git:
  depth: 10000

before_install:
  - composer --verbose self-update
  - composer --version

install:
  - composer --verbose install --prefer-dist
  - composer drupal-scaffold

before_script:
  - git config --global user.email "support@thirdandgrove.com"
  - git config --global user.name "Third and Grove - Travis CI"
  - composer global require drupal/coder:^8.2.12
  - composer global require dealerdirect/phpcodesniffer-composer-installer
  - export PATH="$PATH:$HOME/.composer/vendor/bin"
  - npm install -g gulp

script:
  - ./vendor/bin/phpunit
  - ./private/scripts/tests/phpcs.sh

deploy:
  provider: script
  skip_cleanup: true
  script: private/scripts/deploy/acquia.sh dev
  on:
    branch: develop
